$(function(){
    $('.button_log_out').on("click",function(){
            $.ajax({
            method:'POST',
            url:'./ajax/log_out.php',
            data:{out:'ok'},
            success:function(data){
                if(data=='ok'){
                    window.location.href='index.php'
                }
            }
        })   
    })
})